import Button from "components/components/Button";
import "../styles/sass/main.scss";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header className="header">
          <img src="" alt="" />
          <nav>
            <ul className="header__nav">
              <li>Home</li>
              <li>Shop</li>
              <li>Features</li>
              <li>Pricing</li>
            </ul>
          </nav>
          <Button text="Contact Us" color="secondary" size="md" />
        </header>
        {children}
        <footer className="footer">
          <div>
            <img src="" alt="" />
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Blanditiis quam neque quod vitae et, minima nulla architecto sequi
              incidunt aliquam.
            </p>
            <div>
              <img src="" alt="" />
              <img src="" alt="" />
              <img src="" alt="" />
            </div>
          </div>

          <div>
            <h1>Home</h1>
            <p>Discover</p>
            <p>Explore</p>
            <p>Join</p>
          </div>
          <div>
            <h1>Company</h1>
            <p>Corporation</p>
            <p>Fashion</p>
            <p>About Us</p>
          </div>
          <div>
            <h1>Features</h1>
            <p>Shop</p>
            <p>Cart</p>
            <p>Notigications</p>
            <p>Sales</p>
          </div>
          <div>
            <h1>Contact Us</h1>
            <p>Privacy & Policy</p>
            <p>+009-852-23</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
